name: Deploy to GitHub Pages (root)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Next.js App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./todo-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Clear cache
        run: |
          rm -rf .next || true
          rm -rf node_modules/.cache || true

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint --if-present

      - name: Build Next.js app
        env:
          NEXT_PUBLIC_API_URL: /api
          NODE_ENV: production
        run: |
          npm run build
          echo "Ensure .nojekyll at out root"
          touch out/.nojekyll
          echo "List out root"
          ls -la out/
          echo "List out/_next"
          ls -la out/_next || true
          echo "List out/_next/static"
          ls -la out/_next/static || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./todo-frontend/out

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
